function [Cl,Cd] = lookup(alpha_rad,Re_vec,airfoil)

switch airfoil.type
    case 'sym'
        Re1 = 10000;
        Re2 = 20000;
        Re3 = 40000;
        Re4 = 80000;
        Re5 = 160000;
        Re6 = 360000;
        Re7 = 700000;
        Re8 = 1000000;
        Re9 = 2000000;
        Rea = 5000000;
        Reb = 10000000;
        Cl = alpha_rad;%dummy initialization
        Cd = alpha_rad;%dummy initialization
        for i = 1:length(alpha_rad)
            Re = Re_vec(i);
            alpha = alpha_rad(i)*180/pi;
            %%  Lookup
            if Re<=Re1
                Cl(i)=interp1(airfoil.sym.al.al1,airfoil.sym.cl.cl1,abs(alpha),'linear');
                Cd(i)=interp1(airfoil.sym.al.al1,airfoil.sym.cd.cd1,abs(alpha),'linear');
            elseif Re>Re1 && Re<=Re2
                re(1)=Re1;
                re(2)=Re2;
                cltup(1)=interp1(airfoil.sym.al.al1,airfoil.sym.cl.cl1,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al2,airfoil.sym.cl.cl2,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al1,airfoil.sym.cd.cd1,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al2,airfoil.sym.cd.cd2,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re2)&&(Re<=Re3))
                re(1)=Re2;
                re(2)=Re3;
                cltup(1)=interp1(airfoil.sym.al.al2,airfoil.sym.cl.cl2,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al4,airfoil.sym.cl.cl4,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al2,airfoil.sym.cd.cd2,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al4,airfoil.sym.cd.cd4,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re3)&&(Re<=Re4))
                re(1)=Re3;
                re(2)=Re4;
                cltup(1)=interp1(airfoil.sym.al.al4,airfoil.sym.cl.cl4,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al8,airfoil.sym.cl.cl8,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al4,airfoil.sym.cd.cd4,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al8,airfoil.sym.cd.cd8,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re4)&&(Re<=Re5))
                re(1)=Re4;
                re(2)=Re5;
                cltup(1)=interp1(airfoil.sym.al.al8,airfoil.sym.cl.cl8,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al16,airfoil.sym.cl.cl16,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al8,airfoil.sym.cd.cd8,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al16,airfoil.sym.cd.cd16,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re5)&&(Re<=Re6))
                re(1)=Re5;
                re(2)=Re6;
                cltup(1)=interp1(airfoil.sym.al.al16,airfoil.sym.cl.cl16,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al36,airfoil.sym.cl.cl36,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al16,airfoil.sym.cd.cd16,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al36,airfoil.sym.cd.cd36,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re6)&&(Re<=Re7))
                re(1)=Re6;
                re(2)=Re7;
                cltup(1)=interp1(airfoil.sym.al.al36,airfoil.sym.cl.cl36,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al70,airfoil.sym.cl.cl70,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al36,airfoil.sym.cd.cd36,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al70,airfoil.sym.cd.cd70,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re7)&&(Re<=Re8))
                re(1)=Re7;
                re(2)=Re8;
                cltup(1)=interp1(airfoil.sym.al.al70,airfoil.sym.cl.cl70,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al100,airfoil.sym.cl.cl100,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al70,airfoil.sym.cd.cd70,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al100,airfoil.sym.cd.cd100,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re8)&&(Re<=Re9))
                re(1)=Re8;
                re(2)=Re9;
                cltup(1)=interp1(airfoil.sym.al.al100,airfoil.sym.cl.cl100,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al200,airfoil.sym.cl.cl200,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al100,airfoil.sym.cd.cd100,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al200,airfoil.sym.cd.cd200,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Re9)&&(Re<=Rea))
                re(1)=Re9;
                re(2)=Rea;
                cltup(1)=interp1(airfoil.sym.al.al200,airfoil.sym.cl.cl200,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al500,airfoil.sym.cl.cl500,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al200,airfoil.sym.cd.cd200,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al500,airfoil.sym.cd.cd500,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            elseif ((Re>Rea)&&(Re<=Reb))
                re(1)=Rea;
                re(2)=Reb;
                cltup(1)=interp1(airfoil.sym.al.al500,airfoil.sym.cl.cl500,abs(alpha),'linear');
                cltup(2)=interp1(airfoil.sym.al.al1000,airfoil.sym.cl.cl1000,abs(alpha),'linear');
                cdgup(1)=interp1(airfoil.sym.al.al500,airfoil.sym.cd.cd500,abs(alpha),'linear');
                cdgup(2)=interp1(airfoil.sym.al.al1000,airfoil.sym.cd.cd1000,abs(alpha),'linear');
                Cl(i)=interp1(re,cltup,Re,'linear');
                Cd(i)=interp1(re,cdgup,Re,'linear');
            end
        end
        Cl = Cl.*abs(alpha_rad)./alpha_rad;
    case 'arc'
        alpha_fluent = airfoil.arc.alpha;
        cl_fluent = airfoil.arc.Cl;
        cd_fluent = airfoil.arc.Cd;
        
        alpha_deg = alpha_rad*180/pi;
        Cl=1.1*interp1(alpha_fluent,cl_fluent,alpha_deg,'linear');
        Cd=interp1(alpha_fluent,cd_fluent,alpha_deg,'linear');
end
end